package divisasdiu;


import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;


public class Conversor extends javax.swing.JFrame {
    private Double rate;
    
    public Conversor() throws IOException {
        rate = conversionRate();
        initComponents();
    }
    
    private double conversionRate() throws MalformedURLException, IOException {
        URL url = new URL("https://api.exchangeratesapi.io/latest?symbols=USD");
        
        HttpURLConnection conn = (HttpURLConnection) url.openConnection();
        
        conn.setRequestMethod("GET");
        conn.setRequestProperty("Accept", "application/json");
        BufferedReader br = new BufferedReader(new InputStreamReader(
            (conn.getInputStream())));
        
        String str = br.readLine();

        return Double.parseDouble(str.substring(16, str.indexOf("}")));
        
    }
    
    private boolean onlyDouble(String str){
        Pattern pattern = Pattern.compile("[0-9]+[.][0-9]?|[0-9]+");
        Matcher matcher  = pattern.matcher(str);
        return matcher.matches();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        euroText = new javax.swing.JTextField();
        dolarText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        convertButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        reset = new javax.swing.JButton();
        avisos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pablo Morales Gómez / Carlos Brito Pérez");

        euroText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                euroTextKeyReleased(evt);
            }
        });

        dolarText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dolarTextKeyReleased(evt);
            }
        });

        jLabel1.setText("€");

        jLabel2.setText("$");

        convertButton.setText("Convertir");
        convertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("Conversor");

        reset.setText("Reiniciar");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        avisos.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(avisos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(euroText, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(dolarText, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(convertButton)
                                .addGap(70, 70, 70)
                                .addComponent(reset)))
                        .addGap(0, 94, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(euroText, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dolarText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reset)
                    .addComponent(convertButton))
                .addGap(18, 18, 18)
                .addComponent(avisos, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void euroTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_euroTextKeyReleased
        dolarText.setEnabled(false);
        if(euroText.getText().trim().length() == 0){
            dolarText.setEnabled(true);
            avisos.setText("");
        }
    }//GEN-LAST:event_euroTextKeyReleased

    private void dolarTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dolarTextKeyReleased
        euroText.setEnabled(false);
        if(dolarText.getText().trim().length() == 0){
            euroText.setEnabled(true);
            avisos.setText("");
        }
    }//GEN-LAST:event_dolarTextKeyReleased

    private void convertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertButtonActionPerformed
        avisos.setText("");
        if(euroText.getText().trim().length() == 0 && dolarText.getText().trim().length() > 0) {
            if(onlyDouble(dolarText.getText().trim())) {
                double valor = Double.parseDouble(dolarText.getText().trim())/rate ;
                valor = Math.round(valor*100.0)/100.0;
                euroText.setText(valor + "");
            } else {
                avisos.setText("Introduzca solo números positivos y sin letras");
            }
        } else if(euroText.getText().trim().length() > 0 && dolarText.getText().trim().length() == 0){
            if(onlyDouble(euroText.getText().trim())) {
                double valor = Double.parseDouble(euroText.getText().trim())*rate ;
                valor = Math.round(valor*100.0)/100.0;
                dolarText.setText(valor + "");
            } else {
                avisos.setText("Introduzca solo números positivos y sin letras");
            }
        } else {
            avisos.setText("Introduzca la cantidad de la que desea saber el cambio");
        }
    }//GEN-LAST:event_convertButtonActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        avisos.setText("");
        euroText.setText("");
        euroText.setEnabled(true);
        dolarText.setText("");
        dolarText.setEnabled(true);
    }//GEN-LAST:event_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Conversor().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Conversor.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avisos;
    private javax.swing.JButton convertButton;
    private javax.swing.JTextField dolarText;
    private javax.swing.JTextField euroText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton reset;
    // End of variables declaration//GEN-END:variables
}
